services:
  backend:
    image: wildrent9/staging-server
    ports:
      - 4000:4000
    volumes:
      - ./backend/src:/app/src
    healthcheck:
      test: 'curl --fail --request POST --header ''content-type: application/json'' --url ''http://localhost:4000'' --data ''{"query":"query { __typename }"}'' || exit 1'
      interval: 5s
      timeout: 5s
      retries: 10
    depends_on:
      db:
        condition: service_healthy

  frontend:
    image: wildrent9/staging-client
    restart: always
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    env_file: .env.dev
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src:/app/src
    depends_on:
      backend:
        condition: service_healthy

  db:
    image: postgres
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_PASSWORD: wildrent
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 20
    volumes:
      - pgdata_new1:/var/lib/postgresql/data
  imagesupload:
    build: ./imagesupload
    volumes:
      - ./imagesupload/src:/app/src
      - ./imagesupload/uploads:/app/uploads
    ports:
      - 8000:8000
  nginx:
    image: nginx:1.21.3
    depends_on:
      - backend
      - frontend
    restart: always
    ports:
      # - ${GATEWAY_PORT}:80
      - ${7000}:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - pgdata_new1:/pgdata_new1
      - ./logs:/var/log/nginx
  adminer:
    image: adminer
    ports:
      - 8080:8080

volumes:
  pgdata_new1:
