name: playwright-and-docker-ci

on: push

jobs:
  test-e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Goto e2e and run tests playwright
        run: docker compose up --build && cd e2e && pnpm i && pnpm exec playwright test --exit-code-from e2e
  docker:
      needs: test-e2e
      if: github.ref == 'refs/heads/dev'
      runs-on: ubuntu-latest
      steps:
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v3
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        - name: Build and push
          uses: docker/build-push-action@v4
          with:
            push: true
            context: "{{defaultContext}}:client"
            tags: ${{ secrets.DOCKERHUB_USERNAME }}/github_action_quest_2:latest          
          
          



# on:
#   pull_request

# test-client:
# runs-on: ubuntu-latest
# steps:
#     - name: Check out code
#       uses: actions/checkout@v2
#     - name: Goto client and run tests
#       run: cd client && npm i && npm test